dfinity/chain-fusion-signer

- Dockerfile
- dev-tools.json
We need to build Wasms directly - unfortunately.  So here we install the requisite tools.
- Install `candid-extractor` and `ic-wasm` in the docker builder image.
- Add these two tools to the list that can be installed with `setup`.
See CI
> feat(devops): Install more tools in docker

- scripts/docker-hashes
The docker build emits some strange values at the end.
- Address the xargs warning by telling it to expect nulls in the input
- Address the shasum of the incomple file-of-hashes by omitting that file from those being hashed.
See CI.  No more warnings
> fix(devops): Remove docker-hash warning messages

- .gitignore
docker buildx puts files in an `out` directory.  This is not included in `.gitignore`, so causes spurious warnings about diffs.
- Ignore the out directory.
See CI
> fix(devops): Ignore the docker output file

- Dockerfile
In eth dockerfile, where the libraries are pre-build, `--locked` is not passed, which may cause different libraries to be prebuilt.
- Lock the prebuild dependencies.
See CI
> fix(devops): Lock dependencies in the prebuild

- dfx.json
- init/bitcoin
`dfx deploy` is breaking erratically.  `dfx deploy bitcoin` is breaking consistently.  This is because it is using a remote canister id for `local`, instead of a `specified_id`.
- Remove the bitcoin remote canister id for `local`.
- Add a specified canister id for bitcoin.
- Add a default init arg for bitcoin.
`dfx deploy bitcoin` now works, even ina completely clean repo.  It is yet to be seen whether this resolves the erratic `dfx deploy` breakages.
> fix(devops): Fix local bitcoin deployment

- .github/workflows/check.yml
- .github/workflows/integration.yml
- .github/workflows/pr.yml
- .github/workflows/reproducible-native.yaml
- dfx.json
- scripts/build.signer.sh
We would like to use a custom build command for the signer so that we can add post-build commands.
- Create a custom build command that creates the signer Wasm and candid files.
Existing CI should suffice
> refactor(devops): Use a custom build command for the signer

- scripts/test.backend.sh
- src/signer/tests/it/utils/pocketic.rs
Make tests more reliable instead of relying in relative paths.
* Change the wasm paths to be relative to the cargo workspace instead of relative to the test file.
* Set the env vars in `test.backend.sh` accordingly.
Running `test.backend.sh` with different wasm file names works.
> refactor(devops): Improve WASM source in tests

- Dockerfile
The signer build has been updated; the dockerfile is broken and needs to be updated to match.
- Add the new signer build scripts to the dockerfile
- Use the standard `CARGO_TARGET_DIR` to keep the same behaviour between Docker and native builds.
`./scripts/docker-build` works.  This is exercised in releases but not every PR.
> fix(devops): Update dockerfile

- Dockerfile
- dfx.json
- scripts/build.signer.sh
If we put native and docker builds in the same place, `dfx build signer` and `scripts/docker-build` become interchangeable.
- Put native build artefacts in `out`, in the same place as the docker builds.
See CI
> feat(devops): Put native and docker builds in the same place

- Cargo.lock
- src/example_backend/Cargo.toml
- src/signer/api/Cargo.toml
- src/signer/canister/Cargo.toml
There have been significant changes since the last release, in particular simplifying and cleaning up code.  So it is time for a new release.
- Update the release version to 0.1.4
See CI
> chore(devops): Update the release version to 0.1.4

- dfx.json
- scripts/did.sh
In 2d8f80cb2c47a4b11793e6a29f85ed7aeffc05a0 the signer canister source code was moved.  But `dfx.json` was not updated with the new canister path.
- Update the candid path in `dfx.json`
- Update the .did file generation command to use the new location.
> fix(signer): Update signer candid path

- Cargo.lock
- scripts/build.signer.args.sh
- src/signer/api/Cargo.toml
- src/signer/api/src/impls.rs
- src/signer/api/src/types.rs
- src/signer/canister/signer.did
- src/signer/canister/tests/it/utils/pocketic.rs
We now take payment for API calls.  In mainnet the cycles ledger canister ID is fixed, but in test environments is is helpful, and sometimes necessary, to use a different canister ID.
- Add an optional ledger canister ID to the install arguments.  If not provided, it falls back to the default.
See CI
> feat(signer): Add cycles ledger as an install argument

- dfx.json
The remote canister IDs need to be specified for staging.
- Specify the canister IDs for `internet_identity` and `cycles_ledger` on the staging network.
`dfx build signer --network staging` now works.
> fix(devops): Specify II and cycles ledger canister IDs for staging

- src/signer/api/src/types.rs
- src/signer/canister/signer.did
- src/signer/canister/src/lib.rs
- src/signer/canister/src/sign/bitcoin/bitcoin_api.rs
- src/signer/canister/src/sign/bitcoin/bitcoin_utils.rs
- src/signer/canister/tests/it/address.rs
- src/signer/canister/tests/it/bitcoin.rs
- src/signer/canister/tests/it/utils/mock.rs
Use P2WPKH instead of P2PKH and prepare the address and balance endpoints for bitcoin for frontwards compatibility by introducing request and response types.
* New request and response types for getting the btc address and balance.
* Change the bitcoin utils to return a Result instead of failing.
* Change `caller_btc_address` and `caller_btc_balance` to use params and return Result.
* Change `caller_btc_address` and `caller_btc_balance` to work only for P2WPKH address type.
* Remove `public_key_to_p2pkh_address` and implement `principal_to_p2wpkh_address` instead.
* Change the test to use new request and response types.
* Change expected addresses because they are not the same with P2WPKH type.
> feat(signer): Change API to make it backwards compatible

- Dockerfile
- dfx.json
- scripts/build.signer.sh
Releases should really contain the canister API did.  Users cannot be expected to search through the code to find the .did, especially when the .did file in the code can move.
Add signer.did to the build artefacts and so release.
- Release run from a test release of this PR: https://github.com/dfinity/chain-fusion-signer/actions/runs/10996279002
- Local `dfx build signer` (after creating the ledger canister) includes `out/signer.did`.
- Local docker build includes `out/signer.did`.
> feat(devops): Add signer candid in build artefacts

- src/signer/canister/src/derivation_path.rs
- src/signer/canister/src/lib.rs
- src/signer/canister/src/sign/generic.rs
- src/signer/canister/src/sign/mod.rs
We would like to have a generic signing API, as well as dedicated APIs for specific chains.
- Add a generic signing API and schema.
None yet, but needed!
> feat(signer): Add a generic signing API

- Cargo.lock
- src/example_backend/Cargo.toml
- src/papi/api/Cargo.toml
- src/papi/cycles_ledger_client/Cargo.toml
- src/papi/guard/Cargo.toml
- src/signer/api/Cargo.toml
- src/signer/canister/Cargo.toml
The previous release didn't have an updated candid file.
Update version to 0.2.1
Not necessary.
> chore(signer): New release 0.2.1

- src/signer/api/src/types.rs
- src/signer/canister/signer.did
- src/signer/canister/src/lib.rs
- src/signer/canister/src/sign/bitcoin/tx_utils.rs
Clients should be able to differentiate errors when sending bitcoins and act differently depending on the error.
In this PR, I introduce one more enum in the error response for `btc_caller_send`: `BuildP2wpkhError`.
* New enum `BuildP2wpkhTxError` for error reporting.
* Update signer candid file.
* `build_p2wpkh_transaction` returns a `BuildP2wpkhTxError` instead of a String if error.
Unfortunately we can't add tests for this yet. We need to upgrade pocket-ic when this supports bitcoin.
> feat(signer): Better error reporting in btc_caller_send

- src/signer/canister/src/sign/bitcoin/tx_utils.rs
Security review finding F09. Check also the txid when finding the input value.
* New helper `is_same_outpoint` to compare outpoints of the TxIn and the Utxo.
* Add unit tests for the `get_input_value` helper.
> fix(signer): Check also txid when comparing OutPoints

- src/signer/api/src/types.rs
- src/signer/canister/src/lib.rs
- src/signer/canister/src/sign/bitcoin/tx_utils.rs
Issue raised by the security review F08.
Return an error from `build_p2wpkh_transaction` if remaining amount is less than zero.
* Add entry to `BuildP2wpkhTxError` enum `NotEnoughFunds`.
* Helper to calculate the remaining amount and return error if less than zero.
* Use the helper instead of performing the calculation.
* Remove unnecessary`async` from `build_p2wpkh_transaction`.
* Changes in parameters due to lint issues.
I realized that we could easily write tests for `build_p2wpkh_transaction`. Therefore, I added a test for each case.
> fix(signer): Return error if not enough funds to cover amount plus fee

- .github/workflows/check.yml
- rustfmt.toml
- scripts/fmt-rs
- src/signer/canister/src/lib.rs
- src/signer/canister/src/sign/bitcoin/bitcoin_utils.rs
- src/signer/canister/src/sign/bitcoin/tx_utils.rs
- src/signer/canister/src/sign/eth.rs
- src/signer/canister/src/sign/generic.rs
- src/signer/canister/tests/it/address.rs
- src/signer/canister/tests/it/bitcoin.rs
- src/signer/canister/tests/it/sign.rs
- src/signer/canister/tests/it/utils/pocketic.rs
The rust imports section is formatted erratically.
- Use the nightly rustfmt.
- Group imports by crate.
See CI
> chore(rust): Group imports

- Cargo.lock
- src/example_backend/Cargo.toml
- src/papi/api/Cargo.toml
- src/papi/cycles_ledger_client/Cargo.toml
- src/papi/guard/Cargo.toml
- src/signer/api/Cargo.toml
- src/signer/canister/Cargo.toml
There have been significant updates to the signer, so we would like to cut a release.
- Increment release version
No code changes, but see CI.
> chore(devops): Bump release version to 0.2.3

- .github/workflows/check.yml
- scripts/fmt-rs
If the nightly rust formatter is not installed, formatting fails with an obscure message.
- Provide a helpful error message with instructions for how to install the nightly rust formatter
- Add comments to try to ensure that the help message stays in sync with the install commands used in CI.
We need some new developers to confuse...
See CI for the happy path.
> fix(devops): Helpful message when nightly rust formatter is not installed

- src/signer/api/src/types/eth.rs
- src/signer/canister/signer.did
- src/signer/canister/src/lib.rs
The `SignPrehashRequest` argument calls the prehash "message".  This could get awfully confusing.  It would be best to rectify this before the API is in use.
- Rename the field.
Existing tests should suffice.
> refactor(signer): Rename field in EthSignPrehash

- src/signer/api/src/types.rs
- src/signer/canister/signer.did
- src/signer/canister/src/lib.rs
- src/signer/canister/src/sign/bitcoin/bitcoin_api.rs
- src/signer/canister/tests/it/bitcoin.rs
The bitcoin balance depends on the transactions in the blockchain, and the transactions go over a certain amount of confirmations.
We want to enable clients to query the bitcoin balance of the desired confirmations threshold.
* Add new parameter `min_confirmations` to `GetBalanceRequest`.
* Add new parameter `min_confirmations` in `get_balance`.
* Use new parameter from request to get bitcoin balance in `btc_caller_balance` endpoint.
* New field in candid file.
* Add new parameter in the test for bitcoin balance.
> feat(signer): Add min_confirmations param to btc balance

- scripts/check-pricing
- scripts/did.sh
- src/signer/canister/src/lib.rs
The price set for most API methods was well below the actual mainnet cost.
Note: The cycle cost depends on the size of the subnet and the number of cycles consumed.  The pricing also needs to cover requests in which payment failed.
- Add a command that creates a payment report.
- Update the API prices to about 150% of the cycle cost.
- Note: We can  fine tune the prices later.
TODO: Extract subnet size as a variable and write a test that:
- Checks that the ic deployment subnet size hasn't changed (note: this may potentially change without notice)
- Checks that the cycle cost per subnet node is correct.
After deploying to mainnet, the pricing report should mark every price as OK.
> feat(signer): Correct pricing

- dfx.json
To be able to use the same signer canister build in tests and prod, it is necessary to fix the ID of the cycles ledger.
- In dfx, specify that the cycles ledger canister ID should match prod.
> feat(devops): Fix the cycles ledger canister ID

- .github/workflows/check.yml
- scripts/commit-metadata
- scripts/lint-sh
The shell linter is not currently run in CI.  This means that fixing shell lints can require changes to a PR unrelated to the PR.
- Add a job to CI that runs shfmt.
See CI
> fix(devops): Lint shell scripts in ci

- src/signer/canister/src/lib.rs
- src/signer/canister/tests/it/address.rs
- src/signer/canister/tests/it/bitcoin.rs
The bitcoin API methods need to be paid for.
- Re-enable the payment check in the bitcoin endpoints.
The existing bitcoin tests have been set to #ignore, and will be re-enabled one by one with functioning payments.
> feat(signer): Pay for btc

- .github/actions/build/action.yaml
- scripts/docker-build
- scripts/docker-build.pre
The docker wasm build in GitHub is failing because the step where the commit is put into a file for docker to consume is run in `scripts/docker-build` only, and not in the GitHub docker run.
- Move the pre-docker steps into a dedicated script and call them from both `docker-build` and GitHub.
Pushing the release tag should work with these changes.
> fix(devops): Run prebuild in GitHub

- src/signer/canister/src/lib.rs
When enabling payment for all endpoints, I missed one: `btc_caller_address`
- Uncomment the payment checks for `btc_caller_address`
Existing tests should suffice.  Tests still need to be updated though!
> fix(signer): Require payment everywhere

- dfx.json
- src/signer/canister/signer.did
- src/signer/canister/tests/it/address.rs
- src/signer/canister/tests/it/bitcoin.rs
- src/signer/canister/tests/it/sign.rs
- src/signer/canister/tests/it/utils/mod.rs
- src/signer/canister/tests/it/utils/pic_canister.rs
- src/signer/canister/tests/it/utils/pocketic.rs
The pocket_ic canister tests will need to manage multiple canisters, not just one.  The utilities used to do this, to date, only support one canister.
- Move the PicCanister trait into a separate file and add more methods to it.
- Create a more general version of the canister builder, suitable for use with multiple canisters.
This is used in tests in the `papi` branch, but I am merging this separately to keep the PRs small and reviewable.
> test(signer): Extend the pic canister trait

- scripts/report
We need visibility of what is deployed where.
- Add a command that lists the deployed version and arguments for each network.
Run locally:
```
./scripts/report
...
./scripts/report staging
./scripts/report ic ic staging ic
```
> feat(devops): Add command to print the deployed version of all signers

- scripts/bind/pic/cycles_depositor.hbs
- src/signer/canister/tests/it/address.rs
- src/signer/canister/tests/it/bitcoin.rs
- src/signer/canister/tests/it/canister/cycles_depositor.rs
- src/signer/canister/tests/it/sign.rs
- src/signer/canister/tests/it/utils/pic_canister.rs
The `update()` utility used in `pocket_ic` tests only supports canister methods with a single argument and a single return value.  This is a common case but not the only one.
- Rename `update(..)` to `update_one(..)`, to match functions such as `encode_one()` and `decode_one()`.  This makes space for `update()` to cover general update calls.
Existing tests should suffice.
> refactor(signer): Rename update->update_one

- src/signer/api/src/lib.rs
- src/signer/api/src/methods.rs
- src/signer/canister/src/lib.rs
Tests need to know how much each API method costs.
- Move the signer fee definitions from lib.rs, where they are hard-wired, into a library where they are accessible for tests (and to developers using the signer).
> refactor(signer): Make fees accessible

- src/signer/canister/tests/it/utils/mod.rs
- src/signer/canister/tests/it/utils/pic_canister.rs
- src/signer/canister/tests/it/utils/test_environment.rs
We need a test environment that includes not just the signer itself, but also the cycles ledger and cycles depositor.
- Define a test environment including the signer, multiple canisters, and utilities for funding a user.
- Note: This is largely taken from the `papi` test environment.
This environment is used in tests on a feature branch, but those tests will be merged separately to limit PR size.
> feat(signer): Test environment

- Cargo.lock
- Cargo.toml
To create Schnorr signatures, we need the next version of the `ic-cdk`.
- Update the `ic-cdk` version.
- Remove the unused timers dependency from `Cargo.toml`
> chore(signer): Update ic-cdk

- src/signer/canister/src/lib.rs
The signer canister API documentation is inadequate.
- Make the API functions public.  In this way, the API rustdoc is generated by default.
- Add the most important missing documentation: Mostly that most methods will fail if called by the anonymous user.
> docs(signer): Expose API rustdocs

- src/signer/canister/src/lib.rs
Now that all APIs charge for use, some clippy lints can be re-enabled.
- Remove clippy lints.
> chore(signer): Remove unneeded clippy allows

- rustfmt.toml
- src/signer/api/src/impls.rs
- src/signer/api/src/metrics.rs
- src/signer/api/src/std_canister_status.rs
- src/signer/api/src/types.rs
- src/signer/api/src/types/eth.rs
- src/signer/api/src/types/generic.rs
- src/signer/canister/src/derivation_path.rs
- src/signer/canister/src/impls.rs
- src/signer/canister/src/lib.rs
- src/signer/canister/src/sign/bitcoin/bitcoin_utils.rs
- src/signer/canister/src/sign/bitcoin/fee_utils.rs
- src/signer/canister/src/sign/bitcoin/tx_utils.rs
- src/signer/canister/src/sign/eth.rs
- src/signer/canister/src/sign/generic.rs
- src/signer/canister/src/state.rs
- src/signer/canister/tests/it/bitcoin.rs
- src/signer/canister/tests/it/eth.rs
- src/signer/canister/tests/it/utils/pic_canister.rs
- src/signer/canister/tests/it/utils/test_environment.rs
Niggling formatting differences causing spurious diffs.
- Specify Rust formatting more precisely.
Existing CI checks that formatting is as expected.
> chore(rust): Tighten formatting rules

- .github/workflows/check.yml
- Dockerfile
- scripts/build.signer.args.sh
Canisters installed via proposals need their install arguments to be provided as binary, not candid.
Traditionally in other repositories this conversion has been done as part of the proposal command ([example](https://github.com/dfinity/nns-dapp/blob/main/scripts/nns-dapp/release#L129)), however that is not very reproducible, as (say) a different `didc` could theoretically yield different binary arguments.  When implementing this, we would therefore prefer to generate the binary as part of the docker build.
- Provide binary as well as candid arguments in scripts/build.signer.args.sh
- Add the required tools for the above in the dockerfile
Note: The PR commits have been organized for easy review.
- I have run `./scripts/docker-build` locally and verified that it produces a binary argument …
> feat(devops): Build binary args

- Dockerfile
The dockerfile now creates the binary form of the canister install args, however the sha256 is not printed.
- Print the sha256 of the binary args file.
- Provide the binary args file in the scratch output. (This is the default output; previously it was available only by specifying an earlier docker stage)
Running through the steps for reviewing a proposal I now get:
```
SUCCESS: Docker build has succeeded.
===START_ARTEFACTS===
sha256                                                            size    filename
a99d4a8355c86d2367955d833df83302b5748e6e34898e280e359f9c57541e1f  181     out/signer.args.did
af554044ac038156017c41e85afe1898efbe773593553cf2e38584f237db1316  48      out/commit
ccd50eecb32c38fe8db74c5a84207322ca6dc4ad4c7948579a0300078c074457  8065    out/signer.did …
```
> fix(devops): Print args.bin from dockerfile

- scripts/release
After running the release action, it is necessary to wait for the release github action before proceeding with the next step.
This can be automated. As I waited with the CLI we might as well reuse the cli.
- Wait for the GitHub release action.
I used this in the last release.
> feat(release): Wait for release

- .github/workflows/check.yml
- scripts/proposal-assets
- scripts/proposal-assets.test
The process for creating a proposal includes downloading assets from a release and comparing the SHA256 hashes of these assets with a local build.
- Add a command to  download assets from CI and compute their hashes.
- Used locally in the last release.
- A test is also included and run in CI.
> feat(devops): Download release assets

- dev-tools.json
- scripts/setup
Tool versions are often in the tool download URL.
- Substitute `${VERSION}` for the tool version in the URL.
- Support decompression with a pipe command such as `gunzip`.
Existing setup still works
> refactor(devops): Url version

- dev-tools.json
- scripts/setup
Recent `ic-admin` adds `arg_hash` instead of `arg_hex` to the proposal description.  This is a feature desired by the trusted neurons.
- Specify a version of `ic-admin` to use in `dev-tools.json`.
- Note: Unfortunately `ic-admin` always provides the same response to `--version` so we cannot easily verify that the correct version is being used.
Used locally to install `ic-admin`.
> feat(devops): Specify ic-admin version

- rust-toolchain.toml
- src/signer/canister/src/sign/bitcoin/fee_utils.rs
A new version of Rust is available.
- Update to the latest stable rust version
> chore(rust): Bump rust version

- canister_ids.json
- dfx.json
It is useful to have a test canister running on the same subnet as production, to get accurate pricing and behaviour metrics.
The staging canister operates on a different subnet, and is used extensively by projects other than the chain fusion signer project itself, making it hard to get precise measurements from that canister.
- Define a new beta environment
- Create a new signer canister, on the same subnet as production.
This can be checked by comparing the subnets on the dashboard.
Beta: https://dashboard.internetcomputer.org/canister/uhxml-hyaaa-aaaar-qaoxq-cai
Prod: https://dashboard.internetcomputer.org/canister/grghe-syaaa-aaaar-qabyq-cai
The new canister is configured in cycleops under our team account.
The canister has Orbit as a controller.
> feat(devops): Create beta network

- scripts/build.signer.args.sh
We now have a beta network for the chain fusion signer, but `dfx build signer --network beta` fails.
The deploy code works for `local`, `staging` and `ic` but not for other networks.  
There is a match clause that deals with `ic`, `staging` and everything else.  The branch for "everything else" gets the network from "ENV", defaulting to `local` if `ENV` is not defined.  So it worked for local but not for `beta`.  The `ENV` should be `DFX_NETWORK`.
`beta` will actually be grouped with `ic` in that match clause, however given that the bug has been spotted we might as well use beta to fix that code path first.
- Correct `ENV` to `DFX_NETWORK`.
`dfx build signer --network beta` now works.
> fix(devops): ENV -> DFX_NETWORK

- .github/workflows/check.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/reproducible-native.yaml
- Dockerfile
GitHub is starting to remove 20.04 runners.
- Use Ubuntu 24.04 throughout
For GitHub workflows: See CI
For docker builds: 
```
$ ./scripts/docker-build
...
SUCCESS: Docker build has succeeded.                                                                                                                                                                                                                                                                                                                                                                                             
Assets: …
```
> chore(devops): Use ubuntu 24.04 throughout

- dev-tools.json
It was mentioned during the last release, in December, that the latest `ic-admin` had nice additional features.  The `ic-admin` was already quite new, but let's make sure that we have the desired behaviour.
- Update `ic-admin` to the latest version.
> chore(devops): Bump ic-admin

- dev-tools.json
A newer version of tarpaulin, the rust unit test coverage tool, is available.
- Update tarpaulin.
Existing CI should suffice
> chore(devops): Bump tarpaulin

- .github/workflows/security-audit.yaml
- dev-tools.json
There is a newer version of cargo-audit available.
- Bump cargo-audit to the latest version.
- Add audit cron job.
Actually, there is no audit cron job.  Copied one in.  Ok, now tests should suffice!  See the audit complaining about pocket-ic.  This can be addressed, but in a different PR.
> chore(devops): Bump cargo-audit
